swagger: '2.0'

info:
  title: Home Quest
  description: クソガキを矯正するためのToDoアプリ
  version: "0.0.1"
  license:
    name: "MIT"

host: 192.168.100.209

schemes:
  - http

basePath: /v1

produces:
  - application/json
paths:

  /task:

    get:
      summary: タスクの一覧を取得

      security:
        - api_key: []

      responses:
        200:
          description: タスクの配列
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'

        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

    post:
      summary: タスクを作成

      security:
        - api_key: []

      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Task'

      responses:
        200:
          description: タスク
          schema:
            $ref: '#/definitions/Task'

        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

  /task/{task_uuid}:
    get:
      summary: タスクを取得

      security:
        - api_key: []

      parameters:
        - name: task_uuid
          in: path
          type: string
          description: タスクのUUID
          required: true

      responses:
        200:
          description: タスク
          schema:
            $ref: '#/definitions/Task'

        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

    post:
      summary: タスクの状態を変更

      security:
        - api_key: []

      parameters:
        - name: task_uuid
          in: path
          type: string
          description: タスクのUUID
          required: true
  
        - name: body
          in: body
          description: タスクの状態を表すオブジェクト
          schema:
            $ref: '#/definitions/UpdateTaskState'
          required: true

      responses:
        200:
          description: タスク
          schema:
            $ref: '#/definitions/Task'
        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

    delete:
      summary: タスクを削除

      security:
        - api_key: []

      parameters:
        - name: task_uuid
          in: path
          type: string
          description: タスクのUUID
          required: true

      responses:
        200:
          description: OK

  /signup:
    post:
      summary: 家族アカウントを作成

      security:
        - api_key: []

      parameters:
        - name: body
          in: body
          description: 家族アカウントの情報を表すオブジェクト
          schema:
            $ref: '#/definitions/Signup'

      responses:
        200:
          description: 家族アカウント
          schema:
            $ref: '#/definitions/Signup'

        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

  /signin:
      post:
        summary: サインイン
  
        parameters:
          - in: body
            name: body
            required: true
            schema:
              $ref: '#/definitions/Signin'
  
        responses:
            200:
              description: Signin
              schema:
                $ref: '#/definitions/Signin'
  
            default:
              description: エラー
              schema:
                $ref: '#/definitions/Error'

  /status:
    get:
      summary: ユーザーの状態を取得

      security:
        - api_key: []

      responses:
        200:
          description: ユーザーの状態
          schema:
            $ref: '#/definitions/Status'

        default:
          description: エラー
          schema:
            $ref: '#/definitions/Error'

  /notification:
    get:
      summary: 通知
      security:
        - api_key: []
  
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Notification'
      responses:
          200:
            description: Notification
            schema:
              $ref: '#/definitions/Notification'
  
          default:
            description: エラー
            schema:
              $ref: '#/definitions/Error'

  /child:
    get:
      summary: 子供の一覧を取得
  
      security:
        - api_key: []
  
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Child'
  
      responses:
          200:
            description: Child
            schema:
              $ref: '#/definitions/Child'
  
          default:
            description: エラー
            schema:
              $ref: '#/definitions/Error'
  
    post:
      summary: 子供を人体錬成
  
      security:
        - api_key: []
  
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Child'
  
      responses:
          200:
            description: child配列
            schema:
              $ref: '#/definitions/Child'
  
          default:
            description: エラー
            schema:
              $ref: '#/definitions/Error'

  /child/{child_uuid}:
    delete:
      summary: 子供を消す
      security:
        - api_key: []
  
      parameters:
        - name: child_uuid
          in: path
          type: string
          description: 子供ののUUID
          required: true
  
      responses:
          200:
            description: child
            schema:
              $ref: '#/definitions/Child'
  
          default:
            description: エラー
            schema:
              $ref: '#/definitions/Error'

securityDefinitions:
  api_key:
    type: apiKey
    name: homequest_token
    in: header

definitions:

  Status:
    type: object

    properties:
      family_name:
        type: string
        description: 姓

      given_name:
        type: string
        description: 名

      point:
        type: integer
        description: ポイント

      is_admin:
        type: boolean
        description: ユーザーは管理者である

    required:
      - family_name
      - given_name
      - point
      - is_admin

  Signup:
    type: object

    properties:
      email:
        type: string
        format: email
        description: メールアドレス

      password:
        type: string
        description: パスワード

      login_token:
        type: string
        description: ログイントークン

  Task:
    type: object

    properties:
      title:
        type: string
        description: クエスト名
  
      application_deadline:
        type: integer
        description: 応募期限（UNIX TIME, 秒）

      completion_deadline:
        type: integer
        description: 完了期限（UNIX TIME, 秒）

      point:
        type: integer
        description: ポイント

      difficulty:
        type: integer
        description: 難易度

      description:
        type: string
        description: 詳細

      users:
        type: array
        description: クエストを受けている人のリスト

        items:
          description: クエストを受けている人のUUID
          type: string

      is_complete:
        type: boolean
        description: クエストは完了している

      is_verified:
        type: boolean
        description: 完了は承諾されている

    required:
      - title
      - application_deadline
      - completion_deadline
      - point
      - difficulty
      - description

  UpdateTaskState:
    type: object

    properties:
      is_accept:
        type: boolean
        description: クエストは受注されている

      is_cancel:
        type: boolean
        description: クエストはキャンセルされている

      is_complete:
        type: boolean
        description: クエストは完了されている

      is_reject:
        type: boolean
        description: クエストは断念されている

      is_verified:
        type: boolean
        description: クエストの完了は承認されている

  Signin:
    type: object
  
    properties:
      email:
        type: string
        description: ユーザー名（メールアドレス）
  
      password: 
        type: string
        description: パスワード
  
      token:
        type: string
        description: 固定トークン

  Notification:
    type: object
  
    properties:
      timestamp:
        type: integer
        description: タイムスタンプ(UNIX TIMESTAMP)
      message:
        type: string
        description: 通知のメッセージ

  Child:
    type: object
  
    properties:
      given_name:
        type: string
        description: 名
  
      family_name:
        type: string
        description: 性
  
      login_token:
        type: string
        description: emailの確認についてるアレ

  Error:
    type: object

    properties:
      message:
        type: string

    required:
      - message
